version: '3.8'
services:
  
  hello-world:
    image: nonfiction/hello-world:latest

    deploy:
      mode: global
      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"

        traefik.http.routers.hello-world.rule: "Host(`hello-world.<%= $(bin/get swarm) -%>`)"
        traefik.http.routers.hello-world.entrypoints: "websecure"
        traefik.http.routers.hello-world.tls.certresolver: "resolver-dns"
        traefik.http.routers.hello-world.tls.domains[0].main: "<%= $(bin/get swarm) -%>"
        traefik.http.routers.hello-world.tls.domains[1].sans: "*.<%= $(bin/get swarm) -%>"

        traefik.http.services.hello-world.loadbalancer.server.port: "80"
        traefik.http.services.hello-world.loadbalancer.server.scheme: "http"

    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
