version: '3.8'
services:

  agent:
    image: portainer/agent:latest

    deploy:
      mode: global

    # environment:
    #   AGENT_CLUSTER_ADDR: "tasks.portainer" 

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

    networks:
      - portainer

    # ports:
    #   - target: 9001
    #     published: 9001
    #     protocol: tcp
    #     mode: host

    logging:
      options:
        max-size: "1m"

networks:
  portainer:
    name: portainer
    driver: overlay
    attachable: true
