#!/bin/bash

# Source locally if available OR via curl if not 
include() {
  [ -z "$1" ] && return 1
  if [ -e /root/platform/swarm/$1 ]; then source /root/platform/swarm/$1;
  else source <(curl -fsSL https://github.com/nonfiction/platform/raw/master/swarm/$1); fi
}

# Bash helper functions
include "lib/helpers.sh"

defined $EDITOR || EDITOR=vi
defined $XDG_CONFIG_HOME || XDG_CONFIG_HOME=$HOME/.config
defined $XDG_DATA_HOME || XDG_DATA_HOME=$HOME/.local/share

COMMAND=$1
SWARM=$2
ARGS=${@:3}

mkdir -p "${XDG_DATA_HOME}/swarms"
SWARMFILE="${XDG_DATA_HOME}/swarms/${SWARM}"
NODE=$(node_from_fqdn $SWARM);
DOMAIN=$(domain_from_fqdn $SWARM);


case $COMMAND in

  create | c)
    include "command/create.sh"
    ;;

  delete | d | rm)
    include "command/delete.sh"
    ;;

  edit | e)
    include "command/edit.sh"
    ;;

  inspect | i)
    include "command/inspect.sh"
    ;;

  list | l | ls)
    include "command/list.sh"
    ;;

  primary | p)
    include "command/primary.sh"
    ;;

  replicas | r)
    include "command/replicas.sh"
    ;;

  ssh)
    include "command/ssh.sh"
    ;;

  size | s)
    include "command/size.sh"
    ;;

  update | u)
    include "command/update.sh"
    ;;

  help | h | *)

    echo
    echo "Usage:  swarm COMMAND SWARM [ARGS]"
    echo
    echo "Management Commands:"
    echo "  create"
    echo "  delete"
    echo "  edit"
    echo "  inspect"
    echo "  list"
    echo "  primary"
    echo "  replicas"
    echo "  ssh"
    echo "  size"
    echo "  update"
    echo "  help"
    echo
    ;;
esac
echo
exit
