#!/bin/bash

# Usage examples
# -----------------------
#
# # Add two replicas:
# swarm provision __NODE__.__DOMAIN__ +2
#
# # Remove specific replica:
# swarm provision __NODE__.__DOMAIN__ -__NODE__02
#
# # Promote replica to primary:
# swarm provision __NODE__.__DOMAIN__ ^__NODE__01
#
# # Increase the volume size to 20GB:
# swarm size __NODE__.__DOMAIN__ 20
#
# # Run node configuration and deploy this swarm:
# swarm deploy __NODE__.__DOMAIN__ 
#
# # SSH into the first replica in this swarm:
# swarm ssh __NODE__.__DOMAIN__ __NODE__01


# Workspace configuration
# -----------------------

# Identifies git commits on this workspace
export GIT_USER_NAME="__GIT_USER_NAME__"
export GIT_USER_EMAIL=__GIT_USER_EMAIL__

# Github account
# https://github.com/settings/tokens
export GITHUB_USER=__GITHUB_USER__
export GITHUB_TOKEN=__GITHUB_TOKEN__

# Login password for VS Code/code-server
export CODE_PASSWORD=__CODE_PASSWORD__

# sudo password for "work" user in workspace
export SUDO_PASSWORD=__SUDO_PASSWORD__

# External database cluster credentials
# https://cloud.digitalocean.com/databases
export DB_USER=__DB_USER__
export DB_PASSWORD=__DB_PASSWORD__
export DB_HOST=__DB_HOST__
export DB_PORT=__DB_PORT__


# Node configuration
# -----------------------

# Used by doctl for swarm management & traefik for certificate renewals
export DO_AUTH_TOKEN=__DO_AUTH_TOKEN__

# All nodes in the swarm are have this root password
export ROOT_PASSWORD=__ROOT_PASSWORD__

# Password-protected pages like traefik dashboard
export BASICAUTH_USER=__BASICAUTH_USER__
export BASICAUTH_PASSWORD=__BASICAUTH_PASSWORD__

# This is called by the swarm manager to signal when nodes are ready
# https://api.slack.com/messaging/webhooks
export WEBHOOK=__WEBHOOK__


# Swarm configuration
# These settings cannot be modified after the swarm has been created
# -----------------------

export DROPLET_IMAGE=__DROPLET_IMAGE__
export REGION=__REGION__
export FS_TYPE=__FS_TYPE__

# All nodes in the swarm are accesible via this private key
export ROOT_PRIVATE_KEY=__ROOT_PRIVATE_KEY__
