#!/bin/bash

# Source once locally if available OR via curl if not 
include() {
  [ -z "$1" ] && return 1
  if [ -e /root/platform/swarm/$1 ]; then source /root/platform/swarm/$1;
  else source <(curl -fsSL https://github.com/nonfiction/platform/raw/master/swarm/$1); fi
}

# Bash helper functions
include "lib/helpers.sh"

# Volume helper functions
include "lib/volumes.sh"


# Update primary in case it has changed
if defined $PRIMARY_IP; then
  echo "$PRIMARY_IP" > /etc/primary_ip
fi

# Update webhook in case it has changed
if defined $WEBHOOK; then
  echo "$WEBHOOK" > /etc/webhook
fi

# Ensure all these volumes directories exist
if defined $NODE; then
  volumes_env $NODE
  mkdir -p $GFS_DATA_MNT $(dev_dir $GFS_DATA_DEV) 
  mkdir -p $GFS_WORK_MNT $(dev_dir $GFS_WORK_DEV)
  mkdir -p $DO_BLOCK_MNT
fi

# Set root password
if defined $ROOT_PASSWORD; then
  echo_next "Setting password" 
  for user in root work; do
    echo "${user}:${ROOT_PASSWORD}"
    echo "${user}:${ROOT_PASSWORD}" | chpasswd
  done
fi

# Settings authorized_keys
if defined $ROOT_PUBLIC_KEY; then
  keys="$(curl -sL https://github.com/nonfiction/workspace/raw/main/etc/ssh/authorized_keys)"
  keys=$(echo -e "${ROOT_PUBLIC_KEY}\n${keys}")
  echo_next "Writing /root/.ssh/authorized_keys"
  echo "$keys" | tee /root/.ssh/authorized_keys
  echo_run "cp -f /root/.ssh/authorized_keys /work/.ssh/authorized_keys"
fi

# Update /etc/hosts file
if defined $HOSTS_FILE && defined $NODE; then
  DOMAIN=$(cat /etc/domain)
  echo_next "Setting /etc/hosts on $NODE"
  hosts_self="127.0.1.1 ${NODE}.${DOMAIN} $NODE"
  echo -e "${hosts_self}\n${HOSTS_FILE}" | tee /etc/hosts
fi
                                                                              
# Self-manage /etc/hosts file
if undefined "$(cat /etc/cloud/cloud.cfg | grep manage_etc_hosts)"; then
  echo_next "Appending /etc/cloud/cloud.cfg"
  echo "manage_etc_hosts: False" | tee --append /etc/cloud/cloud.cfg
fi


# Add block storage to fstab
if defined $DO_BLOCK_DEV && defined $DO_BLOCK_MNT; then

  FS_TYPE=$(cat /etc/fs_type)
  entry="${DO_BLOCK_DEV} ${DO_BLOCK_MNT} ${FS_TYPE} defaults,nofail,discard 0 0"
  if undefined "$(cat /etc/fstab | grep "${entry}")"; then
    echo_next "Appending /etc/fstab"
    echo "${entry}" | tee --append /etc/fstab
  fi

  # Mount it right now
  echo_next "Mount block storage"
  echo_run "mount -o discard,defaults,noatime ${DO_BLOCK_DEV} ${DO_BLOCK_MNT}"

fi
