#!/bin/bash

# Bash helper functions
if [ -e /root/platform/swarm/lib/helpers.sh ]; then source /root/platform/swarm/lib/helpers.sh;
else source <(curl -fsSL https://github.com/nonfiction/platform/raw/master/swarm/lib/helpers.sh); fi

# Gluster functions
if [ -e /root/platform/swarm/lib/gluster.sh ]; then source /root/platform/swarm/lib/gluster.sh;
else source <(curl -fsSL https://github.com/nonfiction/platform/raw/master/swarm/lib/gluster.sh); fi

undefined $VOLUME_NAME && VOLUME_NAME="data-gfs"
undefined $VOLUME_MOUNT && VOLUME_MOUNT="/data"

if defined $NAME; then

  # Before resizing with doctl, remove the brick from gluster
  if defined $BEFORE; then
    echo_run "service cron stop"
    echo_run "gluster volume reset-brick ${VOLUME_NAME} $(get_brick $NAME) start"
  fi

  # After resizing with doctl, return the brick to gluster
  if defined $AFTER; then
    echo_run "resize2fs $(get_disk $NAME)"
    echo_run "gluster volume reset-brick ${VOLUME_NAME} $(get_brick $NAME) $(get_brick $NAME) commit force"
    echo_run "service cron start"
  fi

fi
