#!/bin/bash

# Bash helper functions
if [ -e /root/platform/swarm/lib/helpers.sh ]; then source /root/platform/swarm/lib/helpers.sh;
else source <(curl -fsSL https://github.com/nonfiction/platform/raw/master/swarm/lib/helpers.sh); fi

# Stop gluster service
if defined $BEFORE_RESIZE; then
  echo "before resize"
  # echo_run "service glusterd stop"
  # echo_run "umount /data"
fi

# Resize disk, remount, and start gluster again
if defined $VOLUME; then
  disk="/dev/disk/by-id/scsi-0DO_Volume_${VOLUME}"
  mount="/mnt/${VOLUME}"
  # echo_run "resize2fs ${disk} || xfs_growfs ${disk}"
  umount $mount
  echo_run "resize2fs ${disk}"
  echo_run "mount -o discard,defaults,noatime ${disk} ${mount}"
  echo_run "umount /data && mount /data"
  # echo_run "service glusterd start"
fi
