#!/bin/bash

# Source once locally if available OR via curl if not 
include() {
  [ -z "$1" ] && return 1
  if [ -e /root/platform/swarm/$1 ]; then source /root/platform/swarm/$1;
  else source <(curl -fsSL https://github.com/nonfiction/platform/raw/master/swarm/$1); fi
}

# Bash helper functions
include "lib/helpers.sh"


url=$(cat /etc/webhook)
val="[$(hostname -f)] "

if defined $SAY; then
  val+="$SAY"

  if [ "$url" != "__WEBHOOK__" ]; then
    curl -X POST -H "Content-Type: application/json" -d "{\"text\":\"$val\",\"value1\":\"$val\"}" $url
  fi

fi
